/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cart { 'totalInCents' : bigint, 'items' : Array<CartItem> }
export interface CartItem {
  'id' : CartItemId,
  'color' : string,
  'size' : string,
  'productId' : ProductId,
  'quantity' : bigint,
  'priceInCents' : bigint,
}
export type CartItemId = bigint;
export interface Category {
  'id' : CategoryId,
  'name' : string,
  'createdAt' : Timestamp,
  'slug' : string,
  'description' : string,
  'parentId' : [] | [CategoryId],
}
export type CategoryId = bigint;
export interface CreateOrderInput {
  'shippingAddress' : ShippingAddress,
  'stripeSessionId' : [] | [string],
}
export interface CreateProductInput {
  'categoryId' : CategoryId,
  'name' : string,
  'isNewArrival' : boolean,
  'description' : string,
  'variants' : Array<ProductVariant>,
  'isFeatured' : boolean,
  'compareAtPrice' : [] | [bigint],
  'priceInCents' : bigint,
  'images' : Array<ExternalBlob>,
}
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'subtotalInCents' : bigint,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'totalInCents' : bigint,
  'shippingAddress' : ShippingAddress,
  'buyer' : Principal,
  'items' : Array<OrderItem>,
  'stripeSessionId' : [] | [string],
  'shippingInCents' : bigint,
}
export type OrderId = bigint;
export interface OrderItem {
  'color' : string,
  'size' : string,
  'productId' : ProductId,
  'productName' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'paid' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export interface Product {
  'id' : ProductId,
  'categoryId' : CategoryId,
  'name' : string,
  'createdAt' : Timestamp,
  'isNewArrival' : boolean,
  'description' : string,
  'variants' : Array<ProductVariant>,
  'isFeatured' : boolean,
  'compareAtPrice' : [] | [bigint],
  'priceInCents' : bigint,
  'images' : Array<ExternalBlob>,
}
export interface ProductFilter {
  'categoryId' : [] | [CategoryId],
  'inStockOnly' : boolean,
  'color' : [] | [string],
  'size' : [] | [string],
  'maxPriceInCents' : [] | [bigint],
  'searchQuery' : [] | [string],
  'minPriceInCents' : [] | [bigint],
}
export type ProductId = bigint;
export interface ProductVariant {
  'color' : string,
  'size' : string,
  'stock' : bigint,
}
export interface SavedAddress {
  'street' : string,
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'fullName' : string,
  'state' : string,
  'addressLabel' : string,
}
export interface ShippingAddress {
  'street' : string,
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'fullName' : string,
  'state' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateProductInput {
  'id' : ProductId,
  'categoryId' : CategoryId,
  'name' : string,
  'isNewArrival' : boolean,
  'description' : string,
  'variants' : Array<ProductVariant>,
  'isFeatured' : boolean,
  'compareAtPrice' : [] | [bigint],
  'priceInCents' : bigint,
  'images' : Array<ExternalBlob>,
}
export interface UserProfile {
  'displayName' : string,
  'createdAt' : Timestamp,
  'savedAddresses' : Array<SavedAddress>,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addSavedAddress' : ActorMethod<[SavedAddress], boolean>,
  'addToCart' : ActorMethod<[ProductId, string, string, bigint], CartItemId>,
  'addToWishlist' : ActorMethod<[ProductId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createCategory' : ActorMethod<
    [string, string, string, [] | [CategoryId]],
    Category
  >,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrder' : ActorMethod<[CreateOrderInput], Order>,
  'createProduct' : ActorMethod<[CreateProductInput], Product>,
  'deleteCategory' : ActorMethod<[CategoryId], boolean>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Cart>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getNewArrivals' : ActorMethod<[], Array<Product>>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWishlist' : ActorMethod<[], Array<ProductId>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'removeFromCart' : ActorMethod<[CartItemId], boolean>,
  'removeFromWishlist' : ActorMethod<[ProductId], undefined>,
  'removeSavedAddress' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[ProductFilter], Array<Product>>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCartItem' : ActorMethod<[CartItemId, bigint], boolean>,
  'updateCategory' : ActorMethod<
    [CategoryId, string, string, string, [] | [CategoryId]],
    boolean
  >,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], boolean>,
  'updateOrderStripeSession' : ActorMethod<[OrderId, string], boolean>,
  'updateProduct' : ActorMethod<[UpdateProductInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];