/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const SavedAddress = IDL.Record({
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'fullName' : IDL.Text,
  'state' : IDL.Text,
  'addressLabel' : IDL.Text,
});
export const ProductId = IDL.Nat;
export const CartItemId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CategoryId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Category = IDL.Record({
  'id' : CategoryId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'parentId' : IDL.Opt(CategoryId),
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ShippingAddress = IDL.Record({
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'fullName' : IDL.Text,
  'state' : IDL.Text,
});
export const CreateOrderInput = IDL.Record({
  'shippingAddress' : ShippingAddress,
  'stripeSessionId' : IDL.Opt(IDL.Text),
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'color' : IDL.Text,
  'size' : IDL.Text,
  'productId' : ProductId,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'subtotalInCents' : IDL.Nat,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'totalInCents' : IDL.Nat,
  'shippingAddress' : ShippingAddress,
  'buyer' : IDL.Principal,
  'items' : IDL.Vec(OrderItem),
  'stripeSessionId' : IDL.Opt(IDL.Text),
  'shippingInCents' : IDL.Nat,
});
export const ProductVariant = IDL.Record({
  'color' : IDL.Text,
  'size' : IDL.Text,
  'stock' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreateProductInput = IDL.Record({
  'categoryId' : CategoryId,
  'name' : IDL.Text,
  'isNewArrival' : IDL.Bool,
  'description' : IDL.Text,
  'variants' : IDL.Vec(ProductVariant),
  'isFeatured' : IDL.Bool,
  'compareAtPrice' : IDL.Opt(IDL.Nat),
  'priceInCents' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});
export const Product = IDL.Record({
  'id' : ProductId,
  'categoryId' : CategoryId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'isNewArrival' : IDL.Bool,
  'description' : IDL.Text,
  'variants' : IDL.Vec(ProductVariant),
  'isFeatured' : IDL.Bool,
  'compareAtPrice' : IDL.Opt(IDL.Nat),
  'priceInCents' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'createdAt' : Timestamp,
  'savedAddresses' : IDL.Vec(SavedAddress),
  'email' : IDL.Text,
});
export const CartItem = IDL.Record({
  'id' : CartItemId,
  'color' : IDL.Text,
  'size' : IDL.Text,
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
});
export const Cart = IDL.Record({
  'totalInCents' : IDL.Nat,
  'items' : IDL.Vec(CartItem),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const ProductFilter = IDL.Record({
  'categoryId' : IDL.Opt(CategoryId),
  'inStockOnly' : IDL.Bool,
  'color' : IDL.Opt(IDL.Text),
  'size' : IDL.Opt(IDL.Text),
  'maxPriceInCents' : IDL.Opt(IDL.Nat),
  'searchQuery' : IDL.Opt(IDL.Text),
  'minPriceInCents' : IDL.Opt(IDL.Nat),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateProductInput = IDL.Record({
  'id' : ProductId,
  'categoryId' : CategoryId,
  'name' : IDL.Text,
  'isNewArrival' : IDL.Bool,
  'description' : IDL.Text,
  'variants' : IDL.Vec(ProductVariant),
  'isFeatured' : IDL.Bool,
  'compareAtPrice' : IDL.Opt(IDL.Nat),
  'priceInCents' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addSavedAddress' : IDL.Func([SavedAddress], [IDL.Bool], []),
  'addToCart' : IDL.Func(
      [ProductId, IDL.Text, IDL.Text, IDL.Nat],
      [CartItemId],
      [],
    ),
  'addToWishlist' : IDL.Func([ProductId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createCategory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(CategoryId)],
      [Category],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOrder' : IDL.Func([CreateOrderInput], [Order], []),
  'createProduct' : IDL.Func([CreateProductInput], [Product], []),
  'deleteCategory' : IDL.Func([CategoryId], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [Cart], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getNewArrivals' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromCart' : IDL.Func([CartItemId], [IDL.Bool], []),
  'removeFromWishlist' : IDL.Func([ProductId], [], []),
  'removeSavedAddress' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCartItem' : IDL.Func([CartItemId, IDL.Nat], [IDL.Bool], []),
  'updateCategory' : IDL.Func(
      [CategoryId, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(CategoryId)],
      [IDL.Bool],
      [],
    ),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
  'updateOrderStripeSession' : IDL.Func([OrderId, IDL.Text], [IDL.Bool], []),
  'updateProduct' : IDL.Func([UpdateProductInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const SavedAddress = IDL.Record({
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'fullName' : IDL.Text,
    'state' : IDL.Text,
    'addressLabel' : IDL.Text,
  });
  const ProductId = IDL.Nat;
  const CartItemId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CategoryId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Category = IDL.Record({
    'id' : CategoryId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'parentId' : IDL.Opt(CategoryId),
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ShippingAddress = IDL.Record({
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'fullName' : IDL.Text,
    'state' : IDL.Text,
  });
  const CreateOrderInput = IDL.Record({
    'shippingAddress' : ShippingAddress,
    'stripeSessionId' : IDL.Opt(IDL.Text),
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'color' : IDL.Text,
    'size' : IDL.Text,
    'productId' : ProductId,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'subtotalInCents' : IDL.Nat,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'totalInCents' : IDL.Nat,
    'shippingAddress' : ShippingAddress,
    'buyer' : IDL.Principal,
    'items' : IDL.Vec(OrderItem),
    'stripeSessionId' : IDL.Opt(IDL.Text),
    'shippingInCents' : IDL.Nat,
  });
  const ProductVariant = IDL.Record({
    'color' : IDL.Text,
    'size' : IDL.Text,
    'stock' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreateProductInput = IDL.Record({
    'categoryId' : CategoryId,
    'name' : IDL.Text,
    'isNewArrival' : IDL.Bool,
    'description' : IDL.Text,
    'variants' : IDL.Vec(ProductVariant),
    'isFeatured' : IDL.Bool,
    'compareAtPrice' : IDL.Opt(IDL.Nat),
    'priceInCents' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'categoryId' : CategoryId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'isNewArrival' : IDL.Bool,
    'description' : IDL.Text,
    'variants' : IDL.Vec(ProductVariant),
    'isFeatured' : IDL.Bool,
    'compareAtPrice' : IDL.Opt(IDL.Nat),
    'priceInCents' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'createdAt' : Timestamp,
    'savedAddresses' : IDL.Vec(SavedAddress),
    'email' : IDL.Text,
  });
  const CartItem = IDL.Record({
    'id' : CartItemId,
    'color' : IDL.Text,
    'size' : IDL.Text,
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
  });
  const Cart = IDL.Record({
    'totalInCents' : IDL.Nat,
    'items' : IDL.Vec(CartItem),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const ProductFilter = IDL.Record({
    'categoryId' : IDL.Opt(CategoryId),
    'inStockOnly' : IDL.Bool,
    'color' : IDL.Opt(IDL.Text),
    'size' : IDL.Opt(IDL.Text),
    'maxPriceInCents' : IDL.Opt(IDL.Nat),
    'searchQuery' : IDL.Opt(IDL.Text),
    'minPriceInCents' : IDL.Opt(IDL.Nat),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateProductInput = IDL.Record({
    'id' : ProductId,
    'categoryId' : CategoryId,
    'name' : IDL.Text,
    'isNewArrival' : IDL.Bool,
    'description' : IDL.Text,
    'variants' : IDL.Vec(ProductVariant),
    'isFeatured' : IDL.Bool,
    'compareAtPrice' : IDL.Opt(IDL.Nat),
    'priceInCents' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addSavedAddress' : IDL.Func([SavedAddress], [IDL.Bool], []),
    'addToCart' : IDL.Func(
        [ProductId, IDL.Text, IDL.Text, IDL.Nat],
        [CartItemId],
        [],
      ),
    'addToWishlist' : IDL.Func([ProductId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createCategory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(CategoryId)],
        [Category],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOrder' : IDL.Func([CreateOrderInput], [Order], []),
    'createProduct' : IDL.Func([CreateProductInput], [Product], []),
    'deleteCategory' : IDL.Func([CategoryId], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [Cart], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getNewArrivals' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromCart' : IDL.Func([CartItemId], [IDL.Bool], []),
    'removeFromWishlist' : IDL.Func([ProductId], [], []),
    'removeSavedAddress' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCartItem' : IDL.Func([CartItemId, IDL.Nat], [IDL.Bool], []),
    'updateCategory' : IDL.Func(
        [CategoryId, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(CategoryId)],
        [IDL.Bool],
        [],
      ),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
    'updateOrderStripeSession' : IDL.Func([OrderId, IDL.Text], [IDL.Bool], []),
    'updateProduct' : IDL.Func([UpdateProductInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };